### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by hedi-ee**
Taking Martin's suggestion to action. Not sure if it has to stay as a quotation ("").

### CODE REVIEW

**Comment by bedroesb** [comment]
Looks good! Do we also add this to the landing page?

**Comment by bedroesb** [comment]
This one here: https://github.com/hedi-ee/infectious-diseases-toolkit/blob/e4e0f12c6727eb96d70788b1640c372a1291a301/index.html#L23

**Comment by hedi-ee** [comment]
> This one here: https://github.com/hedi-ee/infectious-diseases-toolkit/blob/e4e0f12c6727eb96d70788b1640c372a1291a301/index.html#L23

Yes, please! I just saw that @EvaGarciaAlvarez commented on https://github.com/elixir-europe/infectious-diseases-toolkit/issues/16. But I think Martin's proposal on the active sentence "Find.." is better.

**Comment by hedi-ee** [comment]
I had forgotten to submit the pull request to make the changes in _config.yml regarding the Metadata

**Review by rabuono — APPROVED** [review]
Looks good to me!

**Review by bedroesb — APPROVED** [review]

**Pull request merged**
