### PR TITLE
Change all URLs to use hyphens

### LINKED ISSUE #115: Use hyphens instead of underscores in the url
Google, one of the main search engines, [prefers hyphens](https://developers.google.com/search/docs/crawling-indexing/url-structure#:~:text=Consider%20using%20hyphens%20to%20separate,(%20_%20)%20in%20your%20URLs.) instead of underscores in the url for better interpretation. With RDMkit we are to late in changing this, but with IDTk we are still in time, since the website is still under construction. 

Do we go ahead and change this?

### PR DESCRIPTION
**Pull request by bedroesb**
This will close #115 .

As discussed in the editorial meeting, we would move towards the use of hyphens in the url.

Please check if everything works including the changes from #118 and #117 here: https://bedroesb.github.io/infectious-diseases-toolkit/ :sparkles: 

**WARNING: Merge this PR after #117 and #118 is merged**

TODO after merge:

- [ ] Update URL in the tools Google spreadsheet (website overview)

### CODE REVIEW

**Comment by bedroesb** [comment]
Currently the page_ids and sections in the related pages are still with underscores. Do we want to keep this distinction?

**Comment by bedroesb** [comment]
@martin-nc Good catch, many of these footer links are also not working on the real website 🙈 
Concerning page_ids, yes that is my wish, on the RDMkit and here, but currently not yet the case...

**Review by rabuono — APPROVED** [review]
Thank you!

**Comment by bedroesb** [comment]
lets gooo

**Pull request merged**
