### PR TITLE
Update provenance.md

### PR DESCRIPTION
**Pull request by RudoWittner**
First draft of the provenance page for human clinical and health data.

### CODE REVIEW

**Comment by stain** [comment]
This is a good start! Would you mind adding markdown headers, e.g.

```markdown
# RO Crate

RO Crate is an implementation ..
```

Instead of textual citations, would you make it into hyperlinks?

```markdown
[W3C PROV](https://www.w3.org/TR/prov-overview/) is a..
```

I would do it, but I don't seem to have write-access nor able to approve - perhaps need to be added to elixir-europe/idtk-editors  ?

**Review by stain — CHANGES_REQUESTED** [review]
Thanks! Here are my proposed improvements.

- [x] Change to inline hyperlinks instead of citations
- [x] Make `# headings`
- [x] Add link to https://w3id.org/ro/crate/1.1 for RO-Crate specifications.
- [ ] Remove [image]... screenshot at end

**Review by stain — APPROVED** [review]

**Comment by bedroesb** [comment]
@stain and @RudoWittner Maybe it would be nice to explain what provenance means in Human clinical and health data
? Also explaining which considerations one needs would be a good thing like proposed [here](https://github.com/elixir-europe/infectious-diseases-toolkit/blob/main/TEMPLATE_page.md). Now the content feels like a list of things that come a bit out of the blue, no?

**Comment by IrisVanDam** [comment]
Thanks a lot for showing us how to get started with adding information to a page! I think that a short introduction could be really useful explaining why and how it is used in addition to explaining what it means as suggested by Bert.

**Pull request merged**
