### PR TITLE
Belgium national page 

### PR DESCRIPTION
**Pull request by ShonaCosgrove**

### CODE REVIEW

**Comment by ShonaCosgrove** [comment]
Have filled in the 'national tools and resources' and 'training resources' from the excel sheets but I get this message: Error in user YAML: (<unknown>): mapping values are not allowed in this context at line 11 column 40. 

How can I fix this?

**Comment by bedroesb** [comment]
Seems to look good now! https://shonacosgrove.github.io/infectious-diseases-toolkit/national-resources/belgium

**Comment by ShonaCosgrove** [comment]
Ok thanks Bert! I've just marked it for review :)

**Review by ppalagi — DISMISSED** [review]
hi all,
I have finished reading your page. Well done all! Quite a lot of information, and sometimes they are redundant/repeated. I left my suggestions and comments to try helping to improve the readability.

**Comment by bedroesb** [comment]
@ShonaCosgrove I don't remember if the comments of Patricia were already applied, or still living in a google doc? :) Although maybe Sciensano biased, I do personally think it would be nice if the Belgian page could go life, don't know, my opinion :)

**Comment by ShonaCosgrove** [comment]
Hey @bedroesb, the comments from Patricia have been applied in the Google doc for now. I agree that it would be good to get the page up! I can make the changes in GitHub this afternoon

**Comment by ShonaCosgrove** [comment]
Hey @bedroesb, I made the changes now in the Belgium page, hoped it worked ok and we can publish :)

**Comment by bedroesb** [comment]
looks good!

**Review by IrisVanDam — APPROVED** [review]
Very Sciensano focussed, but the page provides a great overview and once published might be the perfect starting point for other (Belgian) institutes to add additional resources. I added a few suggestions here and there, but nothing major.

**Review by LianeHughes — APPROVED** [review]

**Review by lauportell — APPROVED** [review]

**Pull request merged**
