### PR TITLE
Move to new way of tagging tools

### LINKED ISSUE #198: Move to new way of tagging tools
Tools will be described in the main `tools and resources yaml file`:

image

And be linked from the content using 

`{% tool "tool-id" %}`

This will be visualized in the content like this:

image

On the todo for this: 
- [x] Create IDs for all tools
- [x] Replace tool links in the text with the new snippet
- [x] Adapt content so tools get mentioned at least once @ IDTk
- [x] in national pages, change ref_to_main_resources so that it makes use of ID
- [x] update instance_of to make use of the tool ID
- [x] Update to spreadsheet convertor script to work with the yaml file so the yaml file gets updated with FAIRsharing/TeSS and Bio.tools IDs automatically
- [x] Update documentation in how to add a new tool or resource
- [x] Adding a linter to check if a correct ID is present in the yaml file

### PR DESCRIPTION
**Pull request by bedroesb**
This pull request will close #198, progress tracking will be done on that issue.

Follow the transition live:

https://bedroesb.github.io/infectious-diseases-toolkit/

### CODE REVIEW

**Comment by bedroesb** [comment]
This is actually ready! 

There is only a little but:
I added all tools from the spreadsheet and gave them IDs to make the transition progress of the upcoming pages easier. This means that in the all tools and resources list there will be tools that are not yet tagget in a page, because that page is on the way. Example: #141

**Review by rabuono — APPROVED** [review]
Great!

Approving here so there is no block, but I suggested some minor changes to the "Add new tool or resource" page.

**Comment by bedroesb** [comment]
Thanks a lot!

**Comment by bedroesb** [comment]
here we go! No random errors anymore!

**Pull request merged**
